### ISSUE TITLE
Core? Also CPP

### ISSUE THREAD

**Issue by 26tajeen** [ClassTech/NtpTime#3]
Hi! Thanks for this. Should it work on a Particle Core? Also, bit confused where I define the server and which of the many CPP files I need. I'm used to there being a CPP file, a .H file and then code to use in your INO file. Here there seem to be lots of CPP files, a couple of .H files and a usage.ino. Any pointers on how to get started much appreciated! Thanks

**Comment by ClassTech** [comment]
I’ve never tried it on a Core, but I wouldn’t be surprised if it works.  

You need NtpTime.h and NtpTime.cpp.  It’s a library, so there is no .ino.  See the examples for an example use.

The server defaults to pool.ntp.org <http://pool.ntp.org/>, but you can define a different  one in the NtpTime creator.  For example:  NtpTime(15,”myserver.org”).  See NtpTime.h

— Doug

**Comment by ClassTech** [comment]
Correction:  The server defaults to: time.nist.gov <http://time.nist.gov/>

— Doug
